# Generated by Django 4.1.2 on 2022-10-18 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='/avatar/default.png', upload_to='avatar/')),
                ('name', models.CharField(default='', max_length=256)),
                ('short_bio', models.CharField(default='', max_length=500)),
                ('long_bio', models.TextField(default='')),
                ('advocate_years_exp', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('logo', models.ImageField(blank=True, default='/logo/default.png', upload_to='logo/')),
                ('href', models.URLField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('url', models.URLField(max_length=500)),
                ('advocate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ManyToManyField(null=True, to='api.company'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninja', to=settings.AUTH_USER_MODEL),
        ),
    ]
