# Generated by Django 4.1.2 on 2022-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='company',
            field=models.ManyToManyField(blank=True, to='api.company'),
        ),
    ]
