# Generated by Django 4.1.2 on 2022-10-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_links_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='username',
        ),
        migrations.RemoveField(
            model_name='link',
            name='advocate',
        ),
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='advocate',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.link'),
        ),
        migrations.AddField(
            model_name='link',
            name='github',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='link',
            name='twitter',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='link',
            name='youtube',
            field=models.URLField(default='', max_length=500),
        ),
    ]
