# Generated by Django 4.1.2 on 2022-10-19 11:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_advocate_username_remove_link_advocate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='link',
            field=models.JSONField(blank=True, default=api.models.get_default_links),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
