# Generated by Django 4.1.2 on 2022-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_advocate_company_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
